name: Continuous Integration

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Run Prettier
        run: yarn prettier --write **/*.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run Prettier
